### ISSUE TITLE
Backend Display Stock Prices

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#105]
User Story: https://github.com/lucastanger/aswe-pda/issues/42

As a developer, I want to be able to call the middleware from the frontend, so that I can get all necessary data to display observed stock trends since market opening on the current day (retrospectively). Which stocks are observed must be defined by the user configuration.

**DoD**
- [ ] Feature is merged into dev branch
- [ ] Feature is tested in dev branch
- [ ] Feature is merged into target branch
- [ ] Code Review is finished
- [ ] Travis CI Checks successful
- [ ] Feature is documented (Google Docs and Swagger)
- [ ] Unit tests are finished
