### ISSUE TITLE
Frontend Set Alarm Clock

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#106]
User Story: https://github.com/lucastanger/aswe-pda/issues/34

**Acceptance criteria:**
- [x] Upon opening the goodbye page the alarm clock widget is shown
- [ ] The alarm clock widget shows the first appointment of the next day (if appointment is before noon)
- [ ] The alarm clock widget is NOT shown if there is no appointment before noon for the next day
- [ ] If an appointment is shown, the PDA suggests a time to set the alarm clock (default: 1 hour before appointment)
- [ ] The user has an option to set and unset the alarm clock (toggle button)
- [ ] The alarm clock rings the next day at the displayed time (voice prompt, popup, etc.)
