### ISSUE TITLE
Frontend Display Grade Report

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#112]
User Story: https://github.com/lucastanger/aswe-pda/issues/35

Workflow:
User: "Please show me my grades."
JARVIS: "Which exam/module would you like to see?"
User: "Advanced Software Engineering"
JARVIS: "Your grade for ASWE is 99 points"

**Acceptance criteria**
- [x] The user can ask the PDA to tell them one specific grade from one exam/module.
- [x] Upon asking, the queried grade is shown by the PDA.
- [ ] If the queried grade does not exist, the PDA lets the user know.
