### ISSUE TITLE
Frontend Edit Alarm Clock Time

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#131]
User Story: https://github.com/lucastanger/aswe-pda/issues/34
depends on: https://github.com/lucastanger/aswe-pda/issues/106

Make the alarm clock time in the goodbye page editable.

**Acceptance criteria:**
- [ ] The user can edit the suggested alarm clock time
- [ ] The user can set the time via a voice command
- [ ] The user can edit the time via a GUI popup
