### ISSUE TITLE
Backend Edit Alarm Clock Time

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#132]
User Story: https://github.com/lucastanger/aswe-pda/issues/34 

**DoD**
- [ ] Feature is merged into dev branch
- [ ] Feature is tested in dev branch
- [ ] Feature is merged into target branch
- [ ] Code Review is finished
- [ ] Travis CI Checks successful
- [ ] Feature is documented (Google Docs and Swagger)
- [ ] Unit tests are finished
