### ISSUE TITLE
Frontend Create Appointment

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#134]
User Story: https://github.com/lucastanger/aswe-pda/issues/33

Workflow:
User: "I want to create an appointment"
JARVIS: "When do you want to create the appointment?"
User: "Tomorrow at 14h"
JARVIS: "What should the title of the appointment be?"
User: "Backlog Refinement"
JARVIS: "What should the description of the appintment be?"
User: "Refine the backlog"

**Acceptance criteria:**
- [ ] The user can ask the PDA in the chat to create a new appointment via voice and chat.
- [ ] When the user asks the PDA to create an appointment, it will ask for each required data entry one by one.
- [ ] The required data the user can enter is date, time, title, description.
- [ ] Upon all data being given by the user, the appointment is added to the user's google calendar.
