### ISSUE TITLE
Frontend Display Dining Recommendations

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#138]
User Story: https://github.com/lucastanger/aswe-pda/issues/40

Workflow:
User: "Show me places where I can eat burgers."
JARVIS: "Here are five places near you where you can eat burgers."

**Acceptance criteria:**
- [ ] The user can ask the PDA for a places that serve a specific food.
- [ ] Upon asking the PDA for a dining recommendation, the PDA gives the user a list of recommended food places.
- [ ] The list of recommendations is sorted by rating (descending).
- [ ] The list shows a maximum of up to 5 places.
- [ ] The list shows only places that are currently open.
- [ ] The list of recommendations is shown in the dining recommendations widget.
- [ ] If there are no recommendations for the queried food, the user is informed.
