### ISSUE TITLE
Document Testing Solution

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#185]
Answer the following questions in the technical documentation:

- [x] How do we test?
- [x] How do we automate testing?
- [x] Which parts of the code do we test?
- [x] Which ones do we not test?
- [x] How do we calculate the test coverage?
- [x] What is the final test coverage of the project?
