### ISSUE TITLE
Frontend Display Current News

### ISSUE THREAD

**Issue by Merida31** [lucastanger/aswe-pda#64]
User Story: https://github.com/lucastanger/aswe-pda/issues/41

**Acceptance criteria**

- [x] The user is shown the most recent news of the day upon opening the PDA for the first time of the day.
- [x] The shown news are determined by the users news category preferences.
- [x] Every news headline is shown as a separate element with picture, headline and when it was released.
- [x] The 4 most recent news are shown.
