### ISSUE TITLE
Frontend Display Travel Route Recommendations

### ISSUE THREAD

**Issue by Merida31** [lucastanger/aswe-pda#65]
User Story: https://github.com/lucastanger/aswe-pda/issues/39

**Acceptance criteria**
- [ ] The user can ask the PDA for a Google Maps navigation route.
- [ ] When the user asks the PDA for a navigation, it will ask for each required data entry one by one.
- [ ] The required data the user can enter is destination, transporation mode (on foot, by bike, by car,...), arrival time.
- [ ] Upon entering all required data, the PDA gives the user a recommended route.
- [ ] The recommended route is displayed in the navigation widget.
- [ ] The recommended route consists of a google maps view and the trip information (start, train lines, duration of the trip arrival time,,..)
