### ISSUE TITLE
Frontend Display Current Appointments

### ISSUE THREAD

**Issue by Merida31** [lucastanger/aswe-pda#66]
User Story: https://github.com/lucastanger/aswe-pda/issues/32

**Acceptance Criteria**
- [x] All upcoming appointments for the day are shown to the user upon the first visit of the day.
- [x] All appointments are displayed chronologically.
- [x] Every appointment can be clickable to redirect to the google calendar.
