### ISSUE TITLE
Backend Display Current News

### ISSUE THREAD

**Issue by Merida31** [lucastanger/aswe-pda#68]
User Story: https://github.com/lucastanger/aswe-pda/issues/41

As a developer, I want to be able to call the middleware from the frontend, so that I can get all necessary data to display the news widget with all relevant current news (last 24 hours). All configurations (newspapers, categories) should be automatically fetched from the user configuration.

**DoD**
- [x] Feature is merged into dev branch
- [ ] Feature is tested in dev branch
- [ ] Feature is merged into target branch
- [x] Code Review is finished
- [x] Travis CI Checks successful
- [x] Feature is documented (Google Docs and Swagger)
