### ISSUE TITLE
Frontend Display Music Recap

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#91]
User Story: https://github.com/lucastanger/aswe-pda/issues/37

As a user, I want to be able to view a list of recently played songs and most frequent artists.

**Estimate:** 

**Acceptance criteria**

- [x] The music recap is shown automatically in a popup upon the first visit of the day.
- [x] The music recap shows a list of the most recent (up to) 5 artists the user has listened to in the past 24 hours.
- [x] The music recap shows a list of the most recent (up to) 5 songs the user has listened to in the past 24 hours.
- [x] Clicking a artist redirects you to the spotify page for that artist in a new browser tab.
