### ISSUE TITLE
Backend Display Music Recap 

### ISSUE THREAD

**Issue by Haiyn** [lucastanger/aswe-pda#92]
User Story: https://github.com/lucastanger/aswe-pda/issues/37

As a developer, I want to be able to call the middleware from the frontend, so that I can receive all necessary data to display a overview of the last 5 artists I've listened to.

**DoD**
- [x] Feature is merged into dev branch
- [ ] Feature is tested in dev branch
- [ ] Feature is merged into target branch
- [x] Code Review is finished
- [x] Travis CI Checks successful
- [x] Feature is documented (Google Docs and Swagger)
